import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Biolune',
  description: 'Terms governing your use of the Biolune precision longevity protocol.',
}

export default function TermsOfService() {
  return (
    <>
      <style>{`
        body { padding-top: var(--nav-h); }
        .legal-page { max-width: 720px; margin: 0 auto; padding: 80px 40px; }
        .legal-page h1 { font-size: clamp(28px, 4vw, 44px); margin-bottom: 8px; }
        .legal-meta { font-size: 13px; color: var(--text-muted); margin-bottom: 48px; }
        .legal-page h2 { font-size: 20px; margin-top: 40px; margin-bottom: 12px; }
        .legal-page p, .legal-page li { font-size: 15px; line-height: 1.75; color: var(--text-muted); margin-bottom: 12px; }
        .legal-page ul { padding-left: 20px; margin-bottom: 12px; }
        .legal-page a { color: var(--gold); }
        @media (max-width: 768px) { .legal-page { padding: 48px 20px; } }
      `}</style>

      <div className="legal-page">
        <p className="label" style={{ marginBottom: 12 }}>Legal</p>
        <h1 className="serif">Terms of Service</h1>
        <p className="legal-meta">Last updated: January 2026 · Biolune B.V., Netherlands</p>

        <p>By accessing or using Biolune's website (biolune.eu) or platform services, you agree to be bound by these Terms of Service. Please read them carefully.</p>

        <h2 className="serif">1. Service Description</h2>
        <p>Biolune provides a precision longevity protocol service that analyses biological data (HRV, biomarkers, hormones, sleep data) and generates personalised health recommendations. Biolune is a performance optimisation service — not a medical service. Nothing on this platform constitutes medical advice, diagnosis, or treatment.</p>

        <h2 className="serif">2. Eligibility</h2>
        <p>You must be at least 18 years old and have the legal capacity to enter a contract. By using Biolune, you confirm you meet these requirements.</p>

        <h2 className="serif">3. Subscription and Payment</h2>
        <ul>
          <li>Subscriptions are billed monthly in advance</li>
          <li>Prices are listed in EUR and include applicable VAT</li>
          <li>You may cancel or pause your subscription at any time from your dashboard</li>
          <li>Refunds are not provided for partial months</li>
        </ul>

        <h2 className="serif">4. Your Responsibilities</h2>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate health information</li>
          <li>Consult a qualified physician before making significant changes to your health regime</li>
          <li>Not share your account credentials</li>
          <li>Use the service only for lawful personal purposes</li>
        </ul>

        <h2 className="serif">5. Health Disclaimer</h2>
        <p>Biolune is not a medical provider. Protocols generated by Biolune are not a substitute for professional medical advice, diagnosis, or treatment. Always consult your physician before starting or changing any health programme. If you experience a medical emergency, contact emergency services immediately.</p>

        <h2 className="serif">6. Intellectual Property</h2>
        <p>All content, methodology, software, and materials on this platform are the intellectual property of Biolune B.V. You may not copy, redistribute, or reverse-engineer any part of the service without written consent.</p>

        <h2 className="serif">7. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, Biolune B.V. shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount paid by you in the 3 months preceding the claim.</p>

        <h2 className="serif">8. Governing Law</h2>
        <p>These Terms are governed by the laws of the Netherlands. Any disputes shall be resolved in the courts of Amsterdam.</p>

        <h2 className="serif">9. Contact</h2>
        <p>Questions: <a href="mailto:legal@biolune.eu">legal@biolune.eu</a></p>
      </div>
    </>
  )
}
